### PR TITLE
Minor updates to Typos in Day 1 Google Colab file

### PR DESCRIPTION
**Pull request by martinezlc99**
Hey Tod - these are just some updates I made as part of day 1 during the course.  Great course!

There seems to be a lot of changes introduced by editing the file in VS Code, so understand if you dont accept this pull request based on the amount of noise in the diff.  

Luis

P.S.  Good to see another service academy graduate out there!

### CODE REVIEW

**Comment by martinezlc99** [comment]
Nah

**Comment by todnewman** [comment]
Thanks Luis!  Let me look these over... I'm curious about the VSCode artifacts... I thought at one point that I'd start using VSCode for Jupyter, but I did get annoyed with some small inconsistencies.   But it does look like you're identifying good things.

What Academy and year?  At CGA we talked about "trained initiative", which as the first person who has ever given a pull request on this material, you certainly must possess!  :)

**Comment by todnewman** [comment]
Looks like you closed it, but I'll look into it anyway.

**Comment by martinezlc99** [comment]
Yes, closed the PR to clean up some.  I'll send back once done.

I really love VS Code, and find it does well with a varierty of languages due to the addon "ecosystem".  Maybe not quite as fast as vim =)  

I am USAFA '99.  I have been here in Cedar Rapids since 2007 after leaving active duty.  My wife is from Iowa, so we moved closer to family.  Nobody but me wanted to move back to my hometown of Houston TX.

Excellent class by the way!  Most likely the best class I have taken in my corporate career.

**Pull request closed without merging**
